services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SenhaForte123!
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 30 && 
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SenhaForte123!' -d master -i /docker-entrypoint-initdb.d/setup.sql -C;
      wait"

  adminer:
    image: adminer:latest
    container_name: adminer_web
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
volumes:
  mssql_data:

  